### PR TITLE
Add anchor kibana::begin and add to dependency chains so that module sub-classes are contained

### PR DESCRIPTION
**Pull request by mzahorik**
Pull request acceptance prerequisites:

- [x] Signed the [CLA](https://www.elastic.co/contributor-agreement/) (if not already signed)
- [x] Rebased/up-to-date with base branch
- [x] Updated CHANGELOG.md with patch notes (if necessary)
- [x] Any relevant docs (README.markdown or inline documentation) updated (if necessary)
- [x] Updated CONTRIBUTORS (if you would like attribution)
- [x] Tests pass CI

### CODE REVIEW

**Comment by karmi** [comment]
Hi @mzahorik, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in yout Git [commit](https://github.com/elastic/puppet-kibana/pull/11.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

**Comment by mzahorik** [comment]
It 'twas non-public.  I've updated my profile, thanks!

**Comment by mzahorik** [comment]
It appears the puppet-3.8 version of the spec tests fail due to an backwards-incompatible change in metadata-json-lint introduced in 2.0.0.  I'm not entirely sure how to do conditionals in a Gemfile to fix this, as semantic_puppet needs to be included only on tests < puppet 4.9.0.  See https://github.com/voxpupuli/metadata-json-lint/blob/master/CHANGELOG.md

**Comment by mzahorik** [comment]
By browsing the elastic/elasticsearch module, I found an example of conditional inclusion in the Gemfile of semantic_puppet.  I assume Puppet gem versions track puppet versions, as I use the supplied PUPPET_GEM_VERSION environment variable to infer installed puppet version.

**Comment by tylerjl** [comment]
@mzahorik thank you immensely both for the contribution and fixing my broken tests! This looks good, I'll merge it and get it out in a bugfix release. Thank you for your work!

**Pull request merged**
