### PR TITLE
Backport Module to Puppet 3.8

### PR DESCRIPTION
**Pull request by soxwellfb**
Pull request acceptance prerequisites:

- [x] Signed the [CLA](https://www.elastic.co/contributor-agreement/) (if not already signed)
- [x] Rebased/up-to-date with base branch
- [ ] Updated CHANGELOG.md with patch notes (if necessary)
- [ ] Any relevant docs (README.markdown or inline documentation) updated (if necessary)
- [x] Updated CONTRIBUTORS (if you would like attribution)
- [x] Tests pass CI

Adds support for Puppet 3.8 as per issue  #4 
Not quite sure what to do with the CHANGELOG and docs at this point, not sure how you'd like to proceed with the versioning on a Puppet 3.8 branch or reflect that in the docs.  Haven't added to CONTRIBUTORS yet, either.

CI Testing here: https://travis-ci.org/soxwellfb/puppet-kibana

### CODE REVIEW

**Comment by tylerjl** [comment]
Thanks for putting in the work @soxwellfb, I'll test drive this and report back. I really appreciate the added effort to keep the parameter validation in there 👍 

Regarding a 3.8 branch, it seems like we could either maintain a 3.x and 4.x branch or just let this change become the single mainline branch that we develop on. While separate branches would let us do things like keep the 4.x-style type annotations, the `validate_*` work keeps most of that functionality intact and would let us centralize fixes and iterating features without forking the two (I'm also not sure about the best way to reflect the separate branches on the Forge?)

I'm willing to hear some input regarding 3.x/4.x branches or merging this straight in if people have feedback. Personally I'm leaning towards merging this straight in and then potentially branching off to a 3.x branch down the road when we deprecate puppet 3; the deleted type annotations in this PR are in the git history whenever we're ready to revert them back in for 4.x. /cc #4

**Comment by tylerjl** [comment]
I took the changes for a test drive and even the docs coverage tests seem to work with a `PUPPET_GEM_VERSION` change, so this looks promising.

Here's what I'm thinking next steps are:

* I'm thinking that we default to `~> 4.0` in the Gemfile to test against 4.x as the default version
* We need spec coverage for some of the `validate_config` resources in the catalog, since these are showing up:

      Untouched resources:

      Kibana::Validate_config[elasticsearch.requestHeadersWhitelist]
      Kibana::Validate_config[elasticsearch.ssl.verify]
      Kibana::Validate_config[server.host]
      Kibana::Validate_config[server.port]

  Alternatively you could try and implement your `validate_config.pp` defined type as a native Puppet function (it's not terribly hard to do if you want to take a stab at it)
* If we end up merging this into master in lieu of separate branches, we should create a new set of tests in the travis matrix to run the same tests, just with `PUPPET_GEM_VERSION` set to the other version to get coverage there.

Let me know your thoughts; if there are things in this list you aren't comfortable tinkering with I can take a look.

**Comment by karmi** [comment]
Hi @soxwellfb, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in yout Git [commit](https://github.com/elastic/puppet-kibana/pull/9.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

**Comment by soxwellfb** [comment]
Hi @karmi - I've added the other email address to the my Github profile.

**Comment by soxwellfb** [comment]
Hi @tylerjl ,

I'm not got a strong opinion either way on merging the code to master or to branch. Happy for it be merged straight in.

With regards to the outstanding issues, I've
* set the default Puppet gem back to `~> 4.0`
* converted the defined type to a Puppet function, similar to the stdlib `validate_*` functions
* and I think I've adjusted the Travis matrix correctly get the more builds with the Puppet 3.8.7 Gem,

**Comment by tylerjl** [comment]
This is looking really good @soxwellfb. The acceptance tests are kind of weird in how puppet gets installed, so I'm preparing a PR for your branch to get 3.x properly installed in the acceptance tests, I'll have something for you shortly.

**Comment by soxwellfb** [comment]
Looking at the Travis results 
- Ubuntu 16.04 build issues seem to be a travis issue building the container
- The rspec test is failing with Puppet 3.8.7 because when passing this param `{ :config => { 5601 => nil }}` the nil isn't being converted to `undef` or an empty string, but literally to `"nil"`. Seem to be a known issue, not entirely sure how to fix it.

**Comment by tylerjl** [comment]
The acceptance tests weren't actually running against 3.8 (the PUPPET_GEM_VERSION just changes the puppet gem installed for locally running unit tests, not what's installed on the test machines).

I've submitted a PR for you branch [here](https://github.com/soxwellfb/puppet-kibana/pull/1) that fixes some of the problems, but there's still various failures that are 3.8 related that'll have to be resolved (I fixed some things like removing some ruby methods that can't be guaranteed to be present on 3.x like `File.absolute_path`, and 3.8 just can't be tested anymore on some platforms since the official puppet repos and libraries don't support it anymore)

**Comment by soxwellfb** [comment]
I've merged your changes. Unfortunately I'm going to b away from keyboard for nearly two weeks. In the meantime, I've added you as collaborator to my fork.

**Comment by tylerjl** [comment]
FYI I've fixed the testing side of this PR such that all relevant platforms are tested properly against 3.8. There's still 3.8-specific failures that need to be fixed, but those seem to be solely a part of the unit tests (`rake test` and not a part of the Docker acceptance tests with actual distros). I'll leave those up for fixing by someone else, but from the testing perspective I'm happy to merge at this point once things are green now that CI is thoroughly testing all versions. 🐛

**Comment by soxwellfb** [comment]
Awesome. Changed the Ruby `nil`'s for the `:undef` symbol, as per the puppet-rspec documentation:

> For passing Puppet's `undef` as a paremeter value, you can simply use `:undef` and it will be translated to undef when compiling. 

and that's getting the green lights with Travis, assuming that was your intent with the `nil` values in the first place? Does add a minimum version requirement for the puppet-rspec gem, so updated the `Gemfile` to reflect that.

**Comment by soxwellfb** [comment]
Neat. Thanks for the work you did on the testing coverage, and for being open to backporting to 3.8 in the first place!

**Pull request merged**
