### PR TITLE
Feature dynamic version and paths, solves issues #16 and #10

### PR DESCRIPTION
**Pull request by joernott**
Pull request acceptance prerequisites:

- [x] Signed the [CLA](https://www.elastic.co/contributor-agreement/) (if not already signed)
- [x] Rebased/up-to-date with base branch
- [x] Updated CHANGELOG.md with patch notes (if necessary)
- [x] Any relevant docs (README.markdown or inline documentation) updated (if necessary)
- [x] Updated CONTRIBUTORS (if you would like attribution)
- [x] Tests pass CI

### CODE REVIEW

**Comment by karmi** [comment]
Hi @joernott, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in yout Git [commit](https://github.com/elastic/puppet-kibana/pull/25.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

**Comment by joernott** [comment]
Hmm, I used the same email address to sign the cla, which I used to sign up with github. Most likely, this was a problem with hiding my email in the settings. I now made that email public, so the check should succeed.

**Comment by tylerjl** [comment]
Thanks for the contrbution, @joernott - this is on my radar and I'll review it when I get a chance. If you could, I've recently merged in some fixes for the test suite into master, so if you could updater your branch with the most recent changes on the master branch it should fix the unrelated failures in travis for this PR.

**Comment by joernott** [comment]
Thanks for fixing the tests. I didn't get around to this yesterday. I merged the fixes into the feature branch.

**Comment by joernott** [comment]
Hmm, do you have any idea where else I need to define the use of stdlib apart from metadata.json and .fixtures.yml? It looks like the dependency is not pulled into the tests.

**Comment by tylerjl** [comment]
If you take a look at [the acceptance tests' helper setup code](https://github.com/joernott/puppet-kibana/blob/b7ace4e4cf251cc6b89d5b700102da28827f8622/spec/spec_helper_acceptance.rb#L74) you'll see that `stdlib` (and `apt`) are only copied to Debian-based nodes right now - if you need `stdlib` on each distro type, you can probably just change that to be a simple array of all three fixture modules.

**Comment by tylerjl** [comment]
Hmm, I recently had to test Amazon Linux 2 in the Elasticsearch module, and it does indeed use systemd over sysv. If you take a look at the nodesets for acceptance testing in the Elasticsearch module, there's an entry for Amazon Linux 2 that outlines the testing setup.

**Comment by joernott** [comment]
Updated to be up-to-date with master

**Comment by joernott** [comment]
Merged the upstream changes into the PR

**Comment by tylerjl** [comment]
Hey @joernott, I'm really sorry about the delay in getting around to this but part of the reason for the slow turnaround is that I wasn't really sure whether we'd be keeping the paradigm around multiple instances, and at this point it looks like we'll be pulling that out of the Elasticsearch module, so other modules like puppet-kibana probably won't support it either. I think the path forward for folks wanting to run >1 instance of Kibana or Elasticsearch will be to rely on Docker to run more than one at a time.

With regards to some of the other features in this PR (like the ability to alter user/groups), I'm happy to help get some of those pieces merged if you'd like to re-submit those as separate PRs independent of multiple instance support. If you do really need multiple instances and end up running a fork of the module, let me know and I can help out with any questions you might have, but for now I think this upstream module will just support running a single service for Kibana.

**Pull request closed without merging**
