### PR TITLE
Update hiera yaml to version 5

### PR DESCRIPTION
**Pull request by mmoll**
Pull request acceptance prerequisites:

- [x] Signed the [CLA](https://www.elastic.co/contributor-agreement/) (if not already signed)
- [ ] Rebased/up-to-date with base branch
- [ ] Updated CHANGELOG.md with patch notes (if necessary)
- [ ] Any relevant docs (README.markdown or inline documentation) updated (if necessary)
- [ ] Updated CONTRIBUTORS (if you would like attribution)
- [ ] Tests pass CI

### CODE REVIEW

**Comment by tylerjl** [comment]
Thanks for the PR @mmoll - do you happen to have a link to the Puppet support lifecycle? I'm on board with bumping the minimum required Puppet version if versions < 4.9 are end-of-life (but I can't find documentation about it anywhere)

**Comment by mmoll** [comment]
@tylerjl Unfortunately there seem to be no notes about this, but https://ask.puppet.com/question/33472/puppet-4-open-source-end-of-life-eol/ and https://groups.google.com/forum/#!topic/puppet-users/78ZcVVyuIMQ suggests that even the whole 4.x series is EOL now. However, the 4.10.x branch in Puppetlabs' repo seems still to get updates, (which is still > 4.9).

**Comment by tylerjl** [comment]
Alright @mmoll I hopped into the Puppet community Slack and talked with a product manager and 4.x is dead after the start of 2019, but I don't see a reason to kill 4.x entirely yet - but at the very least moving a version that shipped Hiera 5 sounds reasonable. They suggested supporting >= 4.10 since that's a much more recently-supported version of 4.x, so if you're in agreement, could I ask:

1. Bump the minimum version (and associated tests) to point at 4.10 instead of 4.9, since it sounds like 4.10 is the way to go
2. Make a small note about raising the minimum required Puppet version in the module's CHANGELOG
3. Do the same for the puppet-elasticsearch module PR (elastic/puppet-elasticsearch#1010)?

Thanks for taking the initiative on version bumping here, community help is greatly appreciated :pray:

**Comment by tylerjl** [comment]
Also side-note (that I'm sure you already discerned), the failing Travis test is unrelated so with the changes I mentioned above I'm happy to merge this.

**Comment by mmoll** [comment]
@tylerjl Sure, what's the next version for the changelog? 6.3.2? 6.4.0? 7.0.0? :)

**Comment by mmoll** [comment]
aw, sorry, ignore the qestion, I see the placeholder now

**Comment by mmoll** [comment]
done. :bowtie:

**Comment by tylerjl** [comment]
Thanks a million @mmoll :pray:

**Pull request merged**
